title: "Magnus Eldrup"
description: "Magnus Eldrup is a PhD Candidate in Economics at the University of Copenhagen working on public economics, development, and taxation."
theme: jekyll-theme-primer
url: "https://magnuseldrup.github.io"
